a=set(input("data1: ").split(','))
b=set(input("data2: ").split(','))
c=set(input("data3: ").split(','))
print("set1 sorted:",sorted(list(a)))
print("set2 sorted:",sorted(list(b)))
print("set3 sorted:",sorted(list(c)))
print("is set1 subset of set2?",a.issubset(b))
print("is set2 subset of set1?",b.issubset(a))
print("is set1 subset of set3?",a.issubset(c))
print("is set3 subset of set1?",c.issubset(a))
print("is set2 subset of set3?",b.issubset(c))
print("is set3 subset of set2?",c.issubset(b))