a=set(input("data1: ").split(','))
b=set(input("data2: ").split(','))
c=set(input("data3: ").split(','))
print("engineers:",sorted(list(a)))
print("programmers:",sorted(list(b)))
print("managers:",sorted(list(c)))
print("employees:",sorted(list(a.union(b,c))))
emp=set(list(a)+list(b)+list(c))
e=input("element into engineers: ")
a=list(a)
a.append(e)
a=set(a)
print("engineers:",(sorted(list(a))))
print("employees.issuperset of engineers:",emp.issuperset(a))
print("let us update employees from engineers")
emp.add(e)
print("employees.issuperset of engineers:",emp.issuperset(b))
el=input("element to remove from engineers, programmers, managers, employees: ")
a.discard(el)
print("engineers:",sorted(list(a)))
b.discard(el)
print("programmers:",sorted(list(b)))
c.discard(el)
print("managers:",sorted(list(c)))
emp.discard(el)
print("employees:",sorted(list(emp)))
