dct = {'1':'apple', '2':'orange', '3':'mango', '4':'banana'}
print("dct_keys = dct.keys()")
dct_keys = dct.keys()
print("dct_values = dct.values()")
dct_values = dct.values()
print("dct_keys_list = list(dct_keys)")
dct_keys_list = list(dct_keys)
print("dct_values_list = list(dct_values)")
dct_values_list = list(dct_values)
print("dct_keys_list =", sorted(dct_keys_list))
print("dct_values_list =", sorted(dct_values_list))
print("Combining both the keys and values list using zip");
print("zip(dct_keys_list, dct_values_list)")
zip_result = zip(dct_keys_list, dct_values_list)
print("Creating a list out of the zip result using list function")
zip_result_list = list(zip_result)
print("zip_result_list =", sorted(zip_result_list))
print("Finally creating the dictionary from the zip result list")
dict2 = dict(zip_result_list)
print("dict2 =", sorted(dict2.items()))