a=set(input("data1: ").split(','))
b=set(input("data2: ").split(','))
c=set(input("data3: ").split(','))
print("set1 sorted:",sorted(list(a)))
print("set2 sorted:",sorted(list(b)))
print("set3 sorted:",sorted(list(c)))
l=a.union(b)
print("union of set1, set2:",sorted(list(l)))
print("union of set1, set2, set3:",sorted(list(l.union(c))))
print("set1 | set2:",sorted(list(a|b)))
print("set1 | set2| set3:",sorted(list(a|b|c)))