a=set(input("data1: ").split(','))
b=set(input("data2: ").split(','))
print("symmetric difference:",sorted(list(a.symmetric_difference(b))))
print("set1 ^ set2:",sorted(list(a.symmetric_difference(b))))
print("set1 sorted:",sorted(list(a.symmetric_difference(b))))
print("set2 sorted:",sorted(list(b)))
c=set(input("data3: ").split(','))
d=set(input("data4: ").split(','))
print("set3 after (set3 ^= set4):",sorted(list(c.symmetric_difference(d))))
print("set4 after (set3 ^= set4):",sorted(list(d)))